name = "Aztlan"
uuid = "9c4c8e40-9b86-4413-8bd4-8f41c9509d75"
authors = ["Daniel Enriquez"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
